# Generated by Django 4.2.1 on 2023-06-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Acta N°')),
                ('pub_date', models.DateField()),
                ('process_text', models.CharField(max_length=200)),
                ('type_meet', models.CharField(max_length=20)),
                ('hour', models.TimeField()),
                ('next_meet', models.DateField()),
                ('place', models.CharField(max_length=200)),
            ],
        ),
    ]
