# Generated by Django 4.2.1 on 2023-06-04 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Data publish')),
                ('observations', models.CharField(max_length=200)),
                ('commitment', models.CharField(max_length=200)),
                ('control', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('tittle', models.CharField(max_length=200)),
                ('agreements', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.act')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_job', models.CharField(max_length=200)),
                ('description', models.CharField(default='as', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.CharField(max_length=200)),
                ('attended', models.CharField(max_length=200)),
                ('approve', models.CharField(max_length=200)),
                ('asset', models.BooleanField()),
                ('num_id', models.IntegerField()),
                ('process', models.CharField(max_length=40)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.job')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibledevelopment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('commitment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.development')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.user')),
            ],
        ),
        migrations.CreateModel(
            name='Responsiblecommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.commitment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.user')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.act')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.user', verbose_name='Usuario')),
            ],
        ),
    ]
