# Generated by Django 4.2.1 on 2023-06-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0002_commitment_development_job_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='num',
        ),
    ]
