# Generated by Django 4.2.1 on 2023-06-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0003_remove_act_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='asset',
        ),
        migrations.AddField(
            model_name='act',
            name='next_hour',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='act',
            name='next_place',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='asset',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
