# Generated by Django 4.2.1 on 2023-06-07 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0004_remove_user_asset_act_next_hour_act_next_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_registro.user'),
        ),
    ]
