# Generated by Django 4.2.1 on 2023-06-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0005_development_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='development',
            name='num',
        ),
    ]
