# Generated by Django 4.2.1 on 2023-06-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0006_remove_development_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='num',
            field=models.IntegerField(default=None),
        ),
    ]
