# Generated by Django 4.2.1 on 2023-06-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0008_remove_development_agreements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsibledevelopment',
        ),
    ]
