# Generated by Django 4.2.1 on 2023-06-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0009_delete_responsibledevelopment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_registro.user'),
        ),
        migrations.DeleteModel(
            name='Responsiblecommitment',
        ),
    ]
