# Generated by Django 4.2.1 on 2023-06-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0010_commitment_user_id_delete_responsiblecommitment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitment',
            name='act_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_registro.act'),
        ),
    ]
