# Generated by Django 4.2.1 on 2023-06-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0011_commitment_act_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Typemeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='ident',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Data publish'),
        ),
    ]
