# Generated by Django 4.2.1 on 2023-06-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0012_dependece_typemeet_act_ident_alter_commitment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='hour',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='next_meet',
            field=models.DateField(default=None, null=True),
        ),
    ]
