# Generated by Django 4.2.1 on 2023-06-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0014_alter_job_description_alter_user_approve_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='user',
            name='attended',
        ),
        migrations.AlterField(
            model_name='commitment',
            name='control',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Data publish'),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='observations',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='development',
            name='tittle',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
