# Generated by Django 4.2.1 on 2023-07-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0016_state_development_discussion_development_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='process_text',
            field=models.CharField(editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='act',
            name='pub_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='act',
            name='type_meet',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='act_id',
            field=models.ForeignKey(default=None, editable=False, on_delete=django.db.models.deletion.CASCADE, to='app_registro.act'),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='act_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app_registro.act'),
        ),
        migrations.AlterField(
            model_name='development',
            name='act_id',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='app_registro.act'),
        ),
        migrations.AlterField(
            model_name='development',
            name='num',
            field=models.IntegerField(default=None, editable=False),
        ),
    ]
