# Generated by Django 4.2.1 on 2023-07-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0018_alter_commitment_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitment',
            name='control',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
