# Generated by Django 4.2.1 on 2023-07-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0020_alter_commitment_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='process_text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='act',
            name='type_meet',
            field=models.CharField(max_length=20),
        ),
    ]
