# Generated by Django 4.2.1 on 2023-07-07 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0021_alter_act_process_text_alter_act_type_meet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='pub_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='commitment',
            name='act_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_registro.act'),
        ),
        migrations.AlterField(
            model_name='confirmation',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.act'),
        ),
        migrations.AlterField(
            model_name='development',
            name='act_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_registro.act'),
        ),
        migrations.AlterField(
            model_name='development',
            name='num',
            field=models.IntegerField(default=None),
        ),
    ]
