# Generated by Django 4.2.1 on 2023-07-08 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0022_alter_act_pub_date_alter_commitment_act_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='process',
        ),
        migrations.AddField(
            model_name='confirmation',
            name='job_position',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_registro.job'),
        ),
        migrations.AddField(
            model_name='confirmation',
            name='process',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_registro.process'),
        ),
    ]
