# Generated by Django 4.2.1 on 2023-07-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0023_process_remove_user_job_position_remove_user_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='num_id',
            field=models.IntegerField(default=None),
        ),
    ]
