# Generated by Django 4.2.1 on 2023-07-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0024_alter_user_name_alter_user_num_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_registro.job'),
        ),
    ]
