# Generated by Django 4.2.1 on 2023-08-08 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0027_alter_commitment_commitment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='process_text',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_registro.dependece'),
        ),
        migrations.AlterField(
            model_name='act',
            name='type_meet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_registro.typemeet'),
        ),
    ]
