# Generated by Django 4.2.1 on 2023-08-14 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0028_alter_act_process_text_alter_act_type_meet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmation',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
