# Generated by Django 4.2.1 on 2023-09-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0031_alter_commitment_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='next_hour',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='next_meet',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='act',
            name='next_place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
