# Generated by Django 4.2.1 on 2023-09-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0033_user_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contraseña',
        ),
    ]
