# Generated by Django 4.2.1 on 2023-09-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0034_remove_user_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development',
            name='discussion',
            field=models.CharField(default=' ', max_length=20000, null=True),
        ),
    ]
